repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-merge-conflict
  - id: debug-statements
  - id: no-commit-to-branch
    args: [--branch, main]
  - id: requirements-txt-fixer
- repo: https://github.com/mwouts/jupytext
  rev: v1.14.5  # CURRENT_TAG/COMMIT_HASH
  hooks:
  - id: jupytext
    files: '^notebooks/(.*\.md)$'
    args: [--sync, --set-formats, "myst,ipynb"]
