repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-merge-conflict
  - id: debug-statements
  - id: no-commit-to-branch
    args: [--branch, main]
  - id: requirements-txt-fixer
- repo: https://github.com/mwouts/jupytext
  rev: v1.14.5
  hooks:
  - id: jupytext
    files: '^kaggle-notebooks/notebooks/(.*\.py)$'
    args: [--sync, --set-formats, "py:percent,ipynb"]
- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  - id: black
