version: 2

build:
  os: "ubuntu-20.04"
  apt_packages:
    - libgl1-mesa-glx
    - libxrender1
    - xvfb
    - zip
  tools:
    python: "mambaforge-4.10"
  jobs:
    pre_build:
      # Generate the Sphinx configuration for this Jupyter Book so it builds.
      - "jupyter-book config sphinx notebooks/"

conda:
  environment: environment.yml

sphinx:
  builder: html
  fail_on_warning: false
