name: notebooks
channels:
  - conda-forge
dependencies:
  - getfem==5.4.2
  - icecream==2.1.3
  - ipyvtklink==0.2.3
  - jupyter-book==0.15.1
  - jupyterlab==3.6.2
  - jupytext==1.14.5
  - kaggle==1.5.13
  - matplotlib==3.7.1
  - myst-nb==0.17.1
  - numpy==1.24.2
  - panel==0.14.4
  - pip==23.0.1
  - pip:
    - sphinxcontrib-tikz==0.4.16
  - polars==0.16.16
  - pydata-sphinx-theme==0.13.1
  - pyvista==0.38.5
  - scikit-learn==1.2.2
  - seaborn==0.12.2
  - sphinx-book-theme==1.0.0
  - sphinx==4.5.0
  - statsmodels==0.13.5
